#!/usr/bin/env python3
"""
One-time migration:
  - NBA picks → picks/nba.json (parsed from existing dispatch log in index.html)
  - MLB picks → picks/mlb.json (from settled_picks.csv + picks_log.csv pending entries)

After running this, the dispatch log on the homepage is regenerated by
scripts/render_dispatch.py from these JSON files only.
"""
import csv
import json
import os
import re
from datetime import datetime

REPO = os.path.normpath(os.path.join(os.path.dirname(os.path.abspath(__file__)), ".."))
INDEX = os.path.join(REPO, "index.html")
PICKS_DIR = os.path.join(REPO, "picks")
NBA_OUT = os.path.join(PICKS_DIR, "nba.json")
MLB_OUT = os.path.join(PICKS_DIR, "mlb.json")
SETTLED_CSV = os.path.join(REPO, "mlbsim", "settled_picks.csv")

os.makedirs(PICKS_DIR, exist_ok=True)

MONTHS = {"JAN":1,"FEB":2,"MAR":3,"APR":4,"MAY":5,"JUN":6,"JUL":7,"AUG":8,"SEP":9,"OCT":10,"NOV":11,"DEC":12}


def iso_date(month_abbr_day):
    """'APR 30' → '2026-04-30'."""
    m = re.match(r"(\w{3})\s+(\d+)", month_abbr_day.strip().upper())
    if not m:
        return None
    return f"2026-{MONTHS[m.group(1)]:02d}-{int(m.group(2)):02d}"


# ── NBA: parse existing dispatch log ─────────────────────────────────────────
def migrate_nba():
    with open(INDEX) as f:
        html = f.read()

    # Slice the NBA picks tracker section (skip past CSS selectors that share the class name)
    start = html.find('<details class="blog-card post-nba-picks"')
    end = html.find('<details class="blog-card post-mlb-picks"', start)
    if start < 0 or end < 0:
        print(f"  [WARN] Could not locate NBA picks section (start={start}, end={end})")
        return []
    section = html[start:end]

    picks = []
    pattern = re.compile(
        r'<div class="pick-row\s+(\w+)"[^>]*data-status="(\w+)"[^>]*data-matchup="([^"]+)"[^>]*>(.*?)(?=<div class="pick-row|</details>)',
        re.DOTALL,
    )
    for m in pattern.finditer(section):
        row_cls, status, matchup, body = m.groups()
        date = re.search(r'pr-date">([^<]+)', body)
        side = re.search(r'pr-side[^>]*>([^<]+)', body)
        conf = re.search(r'pr-conf">C:(\d+)', body)
        units = re.search(r'pr-units">(\d+)', body)
        result = re.search(r'pr-result">([^<]*)', body)
        if not (date and side and conf and units):
            continue

        date_iso = iso_date(date.group(1))
        if not date_iso:
            continue
        away, home = matchup.split(" @ ")
        side_text = side.group(1).strip()
        # Parse "NYK -2.5" or "NYK ML" etc
        sm = re.match(r"([A-Z]{2,4})\s+([+-]?\d+\.?\d*|ML)", side_text)
        if not sm:
            continue
        side_team = sm.group(1)
        line_str = sm.group(2)
        if line_str == "ML":
            bet_type, line = "ml", None
        else:
            bet_type, line = "spread", float(line_str)

        result_text = result.group(1).strip() if result else ""
        pl = None
        score = None
        if status == "settled":
            pl_m = re.search(r"([+-]\d+)", result_text)
            if pl_m:
                pl = int(pl_m.group(1))
            # Score sometimes lives in pick-detail just after
            detail_after = section[m.end(): m.end() + 500]
            score_m = re.search(r'pick-detail[^>]*>(\d+\s*-\s*\d+|[A-Z]+\s+\d+\s*-\s*[A-Z]+\s+\d+)', detail_after)
            if score_m:
                score = score_m.group(1).strip()

        if status == "settled":
            new_status = "win" if row_cls == "win" else ("loss" if row_cls == "loss" else "push")
        else:
            new_status = "pending"

        picks.append({
            "id": f"{date_iso}-nba-{away}-{home}-{bet_type}",
            "sport": "nba",
            "date": date_iso,
            "away": away,
            "home": home,
            "matchup": matchup,
            "bet_type": bet_type,
            "side": side_team,
            "line": line,
            "odds": -110 if bet_type == "spread" else None,
            "pick_text": side_text,
            "conf": int(conf.group(1)),
            "units": int(units.group(1)),
            "sim_projection": None,
            "sim_edge": None,
            "status": new_status,
            "result": score,
            "pl": pl,
            "settled_at": "2026-05-01" if new_status != "pending" else None,
        })

    # Dedupe by id, keep last
    seen = {}
    for p in picks:
        seen[p["id"]] = p
    picks = sorted(seen.values(), key=lambda p: (p["date"], p["matchup"]), reverse=True)

    with open(NBA_OUT, "w") as f:
        json.dump(picks, f, indent=2)
    print(f"  NBA: {len(picks)} picks → {NBA_OUT}")
    return picks


# ── MLB: from settled_picks.csv (settled) + picks_log.csv (pending) ──────────
def migrate_mlb():
    picks = []
    # Settled
    if os.path.exists(SETTLED_CSV):
        with open(SETTLED_CSV) as f:
            for r in csv.DictReader(f):
                if r["result"] not in ("W", "L"):
                    continue
                date = r["date"]
                away, home = r["away"], r["home"]
                pick_team = r["pick_team"]
                pick_ml = int(r["pick_ml"])
                pl = float(r["pl"])
                status = "win" if r["result"] == "W" else "loss"
                score = f'{r["away_score"]}-{r["home_score"]}' if r["away_score"] and r["home_score"] else None
                picks.append({
                    "id": f"{date}-mlb-{away}-{home}-ml",
                    "sport": "mlb",
                    "date": date,
                    "away": away,
                    "home": home,
                    "matchup": f"{away} @ {home}",
                    "bet_type": "ml",
                    "side": pick_team,
                    "line": None,
                    "odds": pick_ml,
                    "pick_text": f"{pick_team} ML",
                    "conf": int(r["conf"]),
                    "units": 50,
                    "sim_projection": None,
                    "sim_edge": None,
                    "status": status,
                    "result": score,
                    "pl": round(pl, 2),
                    "settled_at": "2026-05-01",
                })

    # Sort
    picks.sort(key=lambda p: (p["date"], p["matchup"]), reverse=True)
    with open(MLB_OUT, "w") as f:
        json.dump(picks, f, indent=2)
    print(f"  MLB: {len(picks)} picks → {MLB_OUT}")
    return picks


if __name__ == "__main__":
    print("Migrating NBA picks…")
    nba = migrate_nba()
    print("\nMigrating MLB picks…")
    mlb = migrate_mlb()

    nba_w = sum(1 for p in nba if p["status"] == "win")
    nba_l = sum(1 for p in nba if p["status"] == "loss")
    nba_p = sum(1 for p in nba if p["status"] == "pending")
    mlb_w = sum(1 for p in mlb if p["status"] == "win")
    mlb_l = sum(1 for p in mlb if p["status"] == "loss")

    print(f"\n══════════════════════════════════════════")
    print(f"  NBA:  {nba_w}-{nba_l}  ({nba_p} pending)")
    print(f"  MLB:  {mlb_w}-{mlb_l}")
    print(f"══════════════════════════════════════════")
